### ISSUE TITLE
Performance issue with synchrono

### ISSUE THREAD

**Issue by suerion** [eclipseisoffline/customtimecycle#5] opened 2024-10-20 21:08 UTC
Hey, after loading my server, it says, that 

[23:03:17] [Server thread/WARN] (MinecraftServer) Can't keep up! Is the server overloaded? Running 13686ms or 273 ticks behind

mclo.gs said also, there are problems with the mods?

https://mclo.gs/yZhOtu0

https://modrinth.com/mod/synchrono
https://modrinth.com/mod/customtimecycle
```
The mods 'Synchrono' and 'Custom Time Cycle' are incompatible.
[ Line #13](https://mclo.gs/yZhOtu0#L13)
Solutions
Remove the mod 'Synchrono'.
Remove the mod 'Custom Time Cycle'.
```

**Comment by eclipseisoffline** [comment] 2024-10-21 07:07
Hi there, as verarr has said on the issue you made at her repo, the incompatibility is because of a bug in version 0.1.3, which will be fixed in the next release, which hopefully should be in a couple of days.

The performance issues are unlikely to be caused by either of these mods - they're both very light. You have however a lot of other mods installed, which is what could be causing it. You can use a profiler like [Spark](https://spark.lucko.me/) to find which mod causes the most lag.

If that ends up being this mod, please report back here with the Spark report you made and I'll look into it.

**Comment by eclipseisoffline** [comment] 2024-10-22 19:46
Seems like the issue is caused by Synchrono, and looks like it's being fixed, which is great.

Version 0.1.4 of Custom Time Cycle has released, which should fix all incompatibilities.

**Closed by eclipseisoffline** 2024-10-22 19:46 UTC

**Comment by suerion** [comment] 2024-10-22 20:36
Thanks also ;)
